# Site settings
# cd /Users/aviscont/Documents/GitHubGeneral/literaturegeek 
# bundle exec jekyll serve --watch
title: Literature Geek
description: 'digital humanities' 
keywords: "literature geek, digital humanities, Amanda Visconti, digital dissertation, digital humanities dissertation, digital edition, digital Ulysses, dissertation, scholarly building, making, coding, web development, humanities computing, James Joyce, digital Joyce, digital Joycean, Infinite Ulysses"

markdown: kramdown
highlighter: rouge
baseurl: ""
permalink: pretty
permalink: /:year/:month/:day/:title/

sharing :
provider : all

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

paginate: 3
paginate_path: "/page:num"

author:
  name     : Amanda Visconti
  job      : digital humanities professor & research programmer
  bio      : "I envision, prototype, & analyze web interfaces & their user communities, building design & code on a strong research background (Ph.D., M.S.) to innovate social reading, learning, & knowing."
  thumb    : /images/author.jpg
  email    : amandavisconti@gmail.com
  url      : http://www.AmandaVisconti.com
  github   : http://github.com/amandavisconti
  twitter  : http://twitter.com/literature_geek
  linkedin : http://linkedin.com/in/amandavisconti
  
twitter_card: "summary_large_image"
twitter_site: "@literature_geek"

exclude: ["Gemfile", "Gemfile.lock", ".DS_Store"]
