# Site settings
title: Literature Geek  / Amanda Visconti
tagline:             'designing the future of digital+social reading'
description:         'Amanda Visconti is a digital humanist with a strong research background and a focus on innovating, coding, and user testing digital interfaces for social reading, learning, and knowledge-making.<br>New Ph.D. (Literature/Digital Humanities Human-Computer Interaction), University of Michigan Information M.S. (Digital Humanities HCI). MITH digital humanities think tank alum (2009-2015).'
markdown: redcarpet
pygments: true
paginate: 2
paginate_path: ""
baseurl: "/literaturegeek"
# About/contact
author:
  name:              Amanda Visconti
  url:               http://www.AmandaVisconti.com
  email:             visconti@umd.edu
  twitter_username:  literature_geek
  github_username:   amandavisconti

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

sharing:
  provider: twitter
  
gems:
- jekyll-redirect-from