# Site settings
# bundle exec jekyll serve --watch OR # bundle exec jekyll serve --incremental
# Incremental has issues (e.g. isn't updating removed posts from tag.md)
title: Literature Geek
tagline:             'smarter online communities via digital humanities'
description:         'LiteratureGeek.com is the research blog of Dr. Amanda Visconti.' 
markdown: kramdown
highlighter: rouge
baseurl: ""
# About/contact
author:
  name:              Amanda Visconti
  url:               http://www.AmandaVisconti.com
  email:             amandavisconti@gmail.com
  twitter_username:  literature_geek
  github_username:   amandavisconti

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

sharing:
  provider: twitter

gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"